In [1]:
import pandas as pd 
import numpy as np

In [11]:
df = pd.read_excel(r"molecular_property_prediction_datasets.xlsx")
df.head()

,sheet,property,rows,key_columns,task,why_it_matters
0,BBBP,Blood-brain barrier penetration,2050.0,"smiles, p_np (1=penetrant,0=not)",Binary classification,Essential for CNS drug candidates (must cross ...
1,ESOL,Aqueous (water) solubility,1128.0,"smiles, measured log solubility in mols per li...",Regression,Poor solubility is a top reason drug candidate...
2,FreeSolv,Hydration free energy,642.0,"smiles, expt (kcal/mol), calc",Regression,Free energy of solvation relates to how a mole...
3,Lipophilicity,logP (octanol/water partition),4200.0,"smiles, exp",Regression,Core ADME property; affects membrane permeabil...
4,ClinTox,Clinical trial toxicity outcome,1484.0,"smiles, FDA_APPROVED, CT_TOX",Binary classification (2 labels),Directly compares approved drugs vs. candidate...

In [12]:
df.tail()

,sheet,property,rows,key_columns,task,why_it_matters
11,"Each sheet = one self-contained ML task. ""smil...",NaN,NaN,NaN,NaN,NaN
12,Recommended split: use scaffold splitting (gro...,NaN,NaN,NaN,NaN,NaN
13,BACE already ships with ~590 numeric descripto...,NaN,NaN,NaN,NaN,NaN
14,"Official full collection (more datasets: HIV, ...",NaN,NaN,NaN,NaN,NaN
15,Drug-candidate-specific ADMET datasets (absorp...,NaN,NaN,NaN,NaN,NaN

In [13]:
print("null_values",df.isnull().sum())

null_values sheet             2
property          9
rows              9
key_columns       9
task              9
why_it_matters    9
dtype: int64

In [14]:
print("dimension of dataset",df.ndim)
print("shape of dataset",df.shape)

dimension of dataset 2
shape of dataset (16, 6)